#  https://stackoverflow.com/questions/58275418/live-reload-for-thymeleaf-template
#  https://attacomsian.com/blog/spring-boot-auto-reload-thymeleaf-templates

spring:
  # Templates reloading during development
  thymeleaf:
    prefix: file:src/main/resources/templates/
    cache: false

#  # Static resources reloading during development
#  resources:
#    static-locations: file:src/main/resources/static/
#    cache-period: 0

app-config:
  simpleKey: "value"
  allCountriesURL: "https://corona.lmao.ninja/v2/countries"
  singleCountryURL: "https://corona.lmao.ninja/v2/countries/country_name"
  singleCountryHistoryURL: "https://corona.lmao.ninja/v2/historical/country_name"
  allCountryHistoryURL: "https://corona.lmao.ninja/v2/historical?lastdays=30"



